# fly.toml app configuration file generated for nonnative-backend on 2023-11-15T15:12:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nonnative-backend"
primary_region = "otp"

[build]
  image = "ghcr.io/inginerie-software-2023-2024/proiect-inginerie-software-ando-foro/bikes4all-spring-boot:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
